//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPI_use_Tech_Assessment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Password
    {
        public int PasswordID { get; set; }
        public int EmployeeID { get; set; }
        public string EncryptedPassword { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
